qfx:
  mgmt_interface:
    em0:
    ip: DHCP
  loopbacks:
    lo0:
      ip: 192.168.254.2
      mask: 32
  uplinks:
    em4:
      description: TO::vqfx1
      ip: 10.44.1.2
      mask: 24
    em5:
      ip: 10.45.1.2
      mask: 24
  server_interfaces:
    em3:
      ip: 10.10.1.2
      mask: 24

  bgp_global:
    as_number: 65002;
    logging: log-updown
    gr: graceful-restart

  bgp_neighbors:
    vqfx1:
      group: LAB
      type: external
      import_policy: BGP-IN
      export_policy: BGP-OUT      
